[build]
  publish = "out"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"
  NEXT_DISABLE_STATIC_IMAGES = "true"
  DISABLE_METADATA_IMAGES = "true"
  NEXT_DISABLE_METADATA_IMAGES = "true"
  DISABLE_WEBPACK_METADATA_LOADER = "true"
  NEXT_DISABLE_IMAGE_OPTIMIZATION = "true"
  NEXT_DISABLE_FAVICON = "true"
  NEXT_CACHE = ".next/cache"
  NETLIFY_CACHE_NEXTJS = "true"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-DNS-Prefetch-Control = "on"

[[headers]]
  for = "/favicon.ico"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Cache-Control = "public, max-age=3600, s-maxage=3600"

# Redirect for Next.js routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security redirects
[[redirects]]
  from = "/.env"
  to = "/404"
  status = 404

[[redirects]]
  from = "/.env.*"
  to = "/404"
  status = 404